### ISSUE TITLE
Requesting certs for the @ record (or a CNAME pointing to it) in the zone fails

### ISSUE THREAD

**Issue by kendallemm** [molnett/cert-manager-webhook-gandi#7]
I was working on setting up the gandi webhook with cert-manager (1.17.1) and discovered that some of my certificate requests wouldn't progress past the `Present` step for some of my hostnames.  I added in some debugging output and saw that for the failing domains, the `HasTxtRecord` API request looked like this:

```
GET /v5/livedns/domains/example.com/records//TXT HTTP/1.1
```

Note the missing entry before the `TXT`.  This got a 200 status code and an empty array as a response `[]`.

The API requests for the `Present`ations which proceeded looked like:

```
GET /v5/livedns/domains/example.com/records/name/TXT HTTP/1.1
```

And received the expected 404.

All of the domains which were getting stuck were `CNAME`s pointing to the `@` record, or the `@` record itself.  I ended up adjusting the `getDomainAndEntry` function to give a default value if the entry is empty:
```
diff --git a/main.go b/main.go
index 785ea13..a1ab7c8 100644
--- a/main.go
+++ b/main.go
@@ -242,6 +242,9 @@ func (c *gandiDNSProviderSolver) getDomainAndEntry(ch *v1alpha1.ChallengeRequest
        entry := strings.TrimSuffix(ch.ResolvedFQDN, ch.ResolvedZone)
        entry = strings.TrimSuffix(entry, ".")
        domain := strings.TrimSuffix(ch.ResolvedZone, ".")
+       if entry == "" {
+               entry = "@"
+       }
        return entry, domain
 }
```

but perhaps a better place to adjust this would be [in the client code](https://github.com/molnett/cert-manager-webhook-gandi/blob/c6ac1d026c3684492656bd37c4301d59d939fadc/gandiclient.go#L95).

**Comment by bittermandel** [comment]
Hi, thanks for the report! It's odd that entry would be an empty string. Though I could see that happening if the ResolvedFQDN is empty.

Could you provide your Issuer configuration and the full DNS entries you've setup?

**Comment by kendallemm** [comment]
Here's my ClusterIssuer:
```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
  name: gandi-staging
spec:
  acme:
    email: someone@example.com
    privateKeySecretRef:
      name: gandi-acme-secret
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cnameStrategy: Follow
          ingress:
            class: nginx
          webhook:
            groupName: gandi-debug.local
            solverName: gandi
            config:
              rootDomain: ""
              apiKeySecretRef:
                key: api-key
                name: gandi-credentials
```

And the DNS entries:
```
@ 10800 IN SOA ns1.gandi.net. hostmaster.gandi.net. 1741909586 10800 3600 604800 10800
* 10800 IN CNAME example.net.
*.pages 10800 IN CNAME first.example.com.
@ 300 IN A 10.0.0.10
@ 10800 IN CAA 0 issue "letsencrypt.org"
@ 10800 IN MX 20 mail.example.net.
m 600 IN CNAME first.example.com.
stats 600 IN CNAME first.example.com.
```

Note that I've got a pair of domains in there, and I've adjusted the names and the address for the `A` record.

Creating two certificates, one for `example.net` and the other for `sub.example.net` both end up with the following `status` for their respective `Challenge`s:
```yaml
status:
  presented: false
  processing: true
  reason: 'unable to change TXT record: failed updating TXT record: <nil>'
  state: pending
```

I've got the upstream version of the webhook and my modded one happily running side-by-side, and I'm happy to give any further information if you need.

Also, per your comment:
> Though I could see that happening if the ResolvedFQDN is empty.

I _do_ expect that the ResolvedFQDN would be empty if it's the same as the zone -- that is, issuing a certificate for `example.net` in the `example.net.` zone.  If I'm going around this the wrong way in the first place, I would be grateful to be steered in the right direction!
